# render.yaml
services:
  # 1. O Banco de Dados Postgres (Corrigido)
  - type: pserv
    name: desifra-db
    plan: free
    # Os campos 'databaseName' e 'user' foram removidos.
    # A Render irá gerá-los automaticamente.

  # 2. O Redis (Serviço Gerenciado)
  - type: pserv
    name: desifra-redis
    plan: free

  # 3. O Django (Gunicorn)
  - type: web
    name: desifra-web
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: gunicorn valuation.wsgi:application --bind 0.0.0.0:8000
    plan: free
    healthCheckPath: /accounts/login/
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: desifra-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: pserv
          name: desifra-redis
          property: connectionString
      - key: DJANGO_ALLOWED_HOSTS
        generateValue: true
      - key: DJANGO_CSRF_TRUSTED_ORIGINS
        generateValue: true
      - key: DEBUG
        value: False

  # 4. O Celery Worker
  - type: worker
    name: desifra-celery
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: celery -A valuation worker --loglevel=info
    plan: free
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: desifra-db
          property: connectionString
      - key: CELERY_BROKER_URL
        fromService:
          type: pserv
          name: desifra-redis
          property: connectionString